# Generated by Django 5.0.6 on 2024-06-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
