# Generated by Django 5.0.6 on 2024-06-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_textsnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='textsnippet',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
